### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by tobbe01** [sandorgyulai/InAppFramework#3]
Im getting some issues after updating my project to swift3.

Error 1: Ambiguous reference to member 'dataTask(with:completionHandler:)'

let task = URLSession.shared.dataTask(with: storeRequest, completionHandler: { (data, response, error) -> Void in

Error 2:  'jsonObject' produces 'Any', not the expected contextual result type 'AnyObject?'
if let data = data, let jsonResponse: AnyObject = try JSONSerialization.jsonObject(with: data, options: JSONSerialization.ReadingOptions()) {

Error 3: Use of unresolved identifier 'SKErrorPaymentCancelled'
if (transaction.error!.code != SKErrorPaymentCancelled) {

Any chance for some help?

**Comment by sandorgyulai** [comment]
Hello there,
I'm currently working on Swift 3 support, if everything goes well and I have enough time, it will be ready today
