### ISSUE TITLE
Security of purchased products and question about checkWithApple

### ISSUE THREAD

**Issue by francesc-o** [sandorgyulai/InAppFramework#4]
Hi! This is an awesome manager for In-App purchase; I only have two questions. 
If I understood, purchased products are stored with bool - key in UserDefaults: isn't this policy potentially unsafe? It's very simple to access to UserDefaults...
The second question is about checkWithApple in:
`InAppFw.sharedInstance.loadPurchasedProducts(checkWithApple: Bool, completion: ((valid: Bool) -> Void)?)`
Will the check prompt user to insert password, or is it independent?
Thanks

**Comment by sandorgyulai** [comment]
Hello there,
For the first question: Yes thats not the best solution, I will try to create a safer way for them. Combined with the checkWithApple it is not that bad.
For the second: No it won't ask for any passwords, it is just simple network request so we can check the validity of the purchase.

**Comment by francesc-o** [comment]
Ok, thank you very much
